name: flutter_datetime_picker
description: A date time picker for flutter, you can choose date / time / date&time in English Dutch and Chinese, and you can also custom your own picker content
version: 1.5.1
homepage: https://github.com/Realank/flutter_datetime_picker

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
